apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      istio: ingressgateway
  template:
    metadata:
      labels:
        istio: ingressgateway
    spec:
      containers:
        - name: istio-proxy
          image: docker.io/istio/proxyv2:1.19.0
          ports:
            - containerPort: 80
              name: http2
            - containerPort: 443
              name: https
